"""add_extra_images_and_colors_to_products

Revision ID: 9d78bf155c8a
Revises: a3b4c5d6e7f8
Create Date: 2026-06-02 20:20:01.748439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d78bf155c8a'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_product', 'cart_items', ['cart_id', 'product_id'])
    op.add_column('products', sa.Column('extra_images', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('colors', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint('uq_reviews_user_product', 'reviews', ['user_id', 'product_id'])
    op.create_index(op.f('ix_wishlist_items_product_id'), 'wishlist_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.create_unique_constraint('uq_wishlist_user_product', 'wishlist_items', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wishlist_user_product', 'wishlist_items', type_='unique')
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_product_id'), table_name='wishlist_items')
    op.drop_constraint('uq_reviews_user_product', 'reviews', type_='unique')
    op.drop_column('products', 'colors')
    op.drop_column('products', 'extra_images')
    op.drop_constraint('uq_cart_product', 'cart_items', type_='unique')
    # ### end Alembic commands ###
