"""add_payment_fields_to_orders

Revision ID: bf18e3d58819
Revises: 54cba7560446
Create Date: 2026-05-19 13:20:38.339074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf18e3d58819'
down_revision: Union[str, None] = '54cba7560446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=20), server_default='COD', nullable=False))
    op.add_column('orders', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(length=20), server_default='UNPAID', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
